using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Volterp.Infrastructure.Migrations;

public partial class AddProductsAndCategories : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS ""Categories"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""Name"" character varying(50) NOT NULL,
                ""Description"" character varying(200),
                ""CompanyId"" integer NOT NULL,
                ""IsActive"" boolean NOT NULL,
                ""CreatedAt"" timestamp with time zone NOT NULL,
                CONSTRAINT ""PK_Categories"" PRIMARY KEY (""Id"")
            );

            CREATE TABLE IF NOT EXISTS ""Products"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""Code"" character varying(50) NOT NULL,
                ""Name"" character varying(100) NOT NULL,
                ""Description"" character varying(500),
                ""Price"" numeric(18,2) NOT NULL,
                ""Stock"" integer NOT NULL DEFAULT 0,
                ""CategoryId"" integer,
                ""CompanyId"" integer NOT NULL,
                ""IsActive"" boolean NOT NULL,
                ""CreatedAt"" timestamp with time zone NOT NULL,
                ""UpdatedAt"" timestamp with time zone,
                CONSTRAINT ""PK_Products"" PRIMARY KEY (""Id"")
            );
        ");

        migrationBuilder.Sql(@"
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_Categories_Companies_CompanyId') THEN
                    ALTER TABLE ""Categories"" ADD CONSTRAINT ""FK_Categories_Companies_CompanyId"" FOREIGN KEY (""CompanyId"") REFERENCES ""Companies"" (""Id"") ON DELETE RESTRICT;
                END IF;
            END $$;
        ");

        migrationBuilder.Sql(@"
            CREATE INDEX IF NOT EXISTS ""IX_Categories_CompanyId"" ON ""Categories"" (""CompanyId"");
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Categories_Name_CompanyId"" ON ""Categories"" (""Name"", ""CompanyId"");
            CREATE INDEX IF NOT EXISTS ""IX_Products_CompanyId"" ON ""Products"" (""CompanyId"");
        ");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "Products");
        migrationBuilder.DropTable(name: "Categories");
    }
}